name: verseau2-local

services:
  postgres:
    image: postgres:latest
    container_name: verseau2-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: verseau2
    networks:
      - verseau2-network

  s3mock:
    image: adobe/s3mock:latest
    container_name: verseau2-s3mock
    restart: unless-stopped
    ports:
      - '9090:9090'
      - '9191:9191'
    networks:
      - verseau2-network

networks:
  verseau2-network:
    driver: bridge